language: node_js
notifications:
  email: false
  
cache:
  directories:
    - node_modules

node_js:
  - '6'

env:
  - COVERAGE=false

services:
  - mysql
  - postgresql

before_install:
  - npm prune

before_script:
  - mysql -uroot -e 'CREATE DATABASE streamer_test;'
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON streamer_test.* TO 'streamer'@'localhost' IDENTIFIED BY 'streamer1234';"
  - mysql -uroot -e "FLUSH PRIVILEGES;"
  - psql -U postgres -c 'CREATE DATABASE streamer_test;'
  - psql -U postgres -c "CREATE USER streamer PASSWORD 'streamer';"
  - psql -U postgres -c 'CREATE ROLE streamer_role;'
  - psql -U postgres -c 'GRANT streamer_role TO streamer;'
  - psql -U postgres -c 'GRANT ALL ON DATABASE streamer_test TO streamer_role;'

install:
  - npm i
script:
  - npm run codeclimate

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
